from app.models.ai_usage import AiFeature, AiUsageEvent
from app.models.base import Base
from app.models.chat import ChatConversation, ChatMessage, ChatRole
from app.models.classroom import ClassroomCourseLink, ClassroomWorkLink, GoogleAccount
from app.models.groups import Group, GroupMember, Invite, InviteKind, ParentLink, ScheduleSlot
from app.models.homework import (
    Assignment,
    AssignmentQuestion,
    AssignmentStatus,
    Classified,
    Job,
    JobStatus,
    MarkConfidence,
    MarkOverrideAudit,
    QuestionDifficulty,
    QuestionMark,
    QuestionTopic,
    RemarkRequest,
    RemarkRequestStatus,
    Submission,
    SubmissionFile,
    SubmissionStatus,
)
from app.models.lessons import Lesson, LessonObservation, LessonTopic
from app.models.readiness import (
    Assessment,
    AssessmentScore,
    AssessmentType,
    Evidence,
    EvidenceSource,
    ReadinessConfidence,
    ReadinessHistory,
    TopicReadiness,
    TutorObservation,
    TutorPreferences,
)
from app.models.readiness_v2 import (
    AiSynthesisStatus,
    ExaminerReport,
    FactorConfidence,
    FactorEvaluation,
    GradeBoundary,
    Mistake,
    MistakeCategory,
    PastPaper,
    PastPaperAttempt,
    PastPaperQuestion,
    PastPaperQuestionTopic,
    ReadinessFactor,
    ReadinessSnapshot,
    ReadinessWeights,
)
from app.models.crm import ParentCommunication, StudentProfile, StudentSubject, TutorNote
from app.models.knowledge import KnowledgeEntry, KnowledgeEntryKind
from app.models.orgs import Organization
from app.models.reports import Report, ReportAudience, ReportStatus
from app.models.resources import GroupResource, ResourceKind
from app.models.syllabus import Subject, SyllabusUpload, SyllabusUploadStatus, Topic
from app.models.users import User, UserRole

__all__ = [
    "AiFeature",
    "AiSynthesisStatus",
    "AiUsageEvent",
    "Assessment",
    "AssessmentScore",
    "AssessmentType",
    "Assignment",
    "AssignmentQuestion",
    "AssignmentStatus",
    "Base",
    "ChatConversation",
    "ChatMessage",
    "ChatRole",
    "Classified",
    "ClassroomCourseLink",
    "ClassroomWorkLink",
    "Evidence",
    "EvidenceSource",
    "ExaminerReport",
    "FactorConfidence",
    "FactorEvaluation",
    "GradeBoundary",
    "Group",
    "GoogleAccount",
    "GroupMember",
    "GroupResource",
    "Invite",
    "InviteKind",
    "Job",
    "JobStatus",
    "KnowledgeEntry",
    "KnowledgeEntryKind",
    "Lesson",
    "LessonObservation",
    "LessonTopic",
    "MarkConfidence",
    "Mistake",
    "MistakeCategory",
    "Organization",
    "ParentCommunication",
    "ParentLink",
    "PastPaper",
    "PastPaperAttempt",
    "PastPaperQuestion",
    "PastPaperQuestionTopic",
    "QuestionDifficulty",
    "MarkOverrideAudit",
    "QuestionMark",
    "RemarkRequest",
    "RemarkRequestStatus",
    "QuestionTopic",
    "ReadinessConfidence",
    "ReadinessFactor",
    "ReadinessHistory",
    "ReadinessSnapshot",
    "ReadinessWeights",
    "Report",
    "ReportAudience",
    "ReportStatus",
    "ResourceKind",
    "ScheduleSlot",
    "StudentProfile",
    "StudentSubject",
    "Subject",
    "Submission",
    "SubmissionFile",
    "SubmissionStatus",
    "SyllabusUpload",
    "SyllabusUploadStatus",
    "Topic",
    "TopicReadiness",
    "TutorNote",
    "TutorObservation",
    "TutorPreferences",
    "User",
    "UserRole",
]
