"""The precomputed narrative — stored plain-prose paragraphs for the tutor's
home / class page (about a class) and the parent screen (about a child).

Spec §8: the narrative is present when the surface opens; no primary surface
waits on a model to render its primary content. So the text is generated by a
background job and stored (models/narrative.py); surfaces read the latest row.
Contrast POST /groups/{id}/brief, which builds the same kind of text live and
discards it.

Two triggers, deliberately different in shape:

- The class narrative enqueues when marked evidence lands for that class, at the
  tail of the evidence build (services/marking.record_marks_as_evidence).
- The parent narrative refreshes weekly by SWEEP, not by a self-perpetuating
  chain. A chain would keep the whole schedule inside one job row, and
  workers/jobs.py sets status=failed at MAX_ATTEMPTS with nothing watching it —
  so one transient AI outage across the retry window would end a parent's
  updates permanently and silently. The sweep re-derives who is due from the
  narratives table every run (BE-9), so a failed sweep costs one cycle and
  self-corrects; a failed individual narrative costs one cycle for one student.

Everything here is gated on settings.narrative_enabled — the kill switch that
stops new narratives while leaving stored ones readable.
"""

import logging
from datetime import datetime, timedelta, timezone

from sqlalchemy import distinct, func, select
from sqlalchemy.ext.asyncio import AsyncSession

from app.config import get_settings
from app.db import async_session
from app.models import (
    AiFeature,
    Evidence,
    FactorConfidence,
    FactorEvaluation,
    Group,
    GroupMember,
    Job,
    JobStatus,
    Narrative,
    NarrativeAudience,
    ReadinessFactor,
    Subject,
    Topic,
    User,
    UserRole,
)
from app.schemas.readiness import SubjectReadiness
from app.services.ai import AIUnavailableError, record_usage, text_complete
from app.services.class_readiness import class_readiness, weak_topic_means
from app.services.evidence import COUNTS_FOR_READINESS
from app.services.grade_boundaries import boundaries_for, org_boundaries
from app.services.grades import grade_band
from app.services.knowledge import resolve_org_tutor_id
from app.services.prompts import get_prompt
from app.services.readiness_summary_v2 import build_summary_v2

log = logging.getLogger("narrative")

CLASS_NARRATIVE_JOB = "generate_narrative"
SWEEP_JOB = "sweep_parent_narratives"

DIRECTION_WORDS = {"up": "improving", "down": "declining", "flat": "steady", None: "no trend yet"}


def _aware(value: datetime | None) -> datetime | None:
    """SQLite hands back tz-naive datetimes where Postgres returns aware, and
    comparing the two raises. The stored value is UTC either way."""
    if value is None:
        return None
    return value if value.tzinfo is not None else value.replace(tzinfo=timezone.utc)


# --------------------------------------------------------------------------- #
# Reading the latest stored narrative (also used by the PR 15 read endpoints).
# --------------------------------------------------------------------------- #


async def latest_narrative(
    session: AsyncSession,
    *,
    audience: NarrativeAudience,
    organization_id: int,
    group_id: int | None = None,
    student_id: int | None = None,
) -> Narrative | None:
    """The most recent narrative for one target, ordered by id (not generated_at)
    so a manual regenerate racing the sweep resolves deterministically."""
    stmt = select(Narrative).where(
        Narrative.organization_id == organization_id,
        Narrative.audience == audience,
    )
    if audience is NarrativeAudience.tutor_class:
        stmt = stmt.where(Narrative.group_id == group_id)
    else:
        stmt = stmt.where(Narrative.student_id == student_id)
    return await session.scalar(stmt.order_by(Narrative.id.desc()).limit(1))


# --------------------------------------------------------------------------- #
# Grounding — facts already computed from real evidence, never invented.
# --------------------------------------------------------------------------- #


async def _latest_evidence_at_for_group(session: AsyncSession, group: Group) -> datetime | None:
    return _aware(
        await session.scalar(
            select(func.max(Evidence.occurred_at))
            .select_from(Evidence)
            .join(Topic, Topic.id == Evidence.topic_id)
            .join(GroupMember, GroupMember.student_id == Evidence.student_id)
            .where(
                GroupMember.group_id == group.id,
                Topic.subject_id == group.subject_id,
                COUNTS_FOR_READINESS,
            )
        )
    )


async def _latest_evidence_at_for_student(
    session: AsyncSession, student_id: int
) -> datetime | None:
    return _aware(
        await session.scalar(
            select(func.max(Evidence.occurred_at)).where(
                Evidence.student_id == student_id, COUNTS_FOR_READINESS
            )
        )
    )


# Self-declared data is labelled wherever it is shown (PROD-8, UX-20), and a
# model is an audience too: without this the prompt would pass an estimate-backed
# score off as marked evidence in a paragraph a parent reads.
ESTIMATE_LABEL = " (includes the tutor's starting estimate, not marked work)"


def _estimate_note(s: SubjectReadiness) -> str:
    return ESTIMATE_LABEL if any(t.tutor_estimate for t in s.topics) else ""


async def _class_grounding(session: AsyncSession, group: Group) -> str:
    """What the class paragraph is grounded in — the **shared** class
    aggregation (services/class_readiness.py), the one the class brief, Group
    Analytics and the class page read.

    It used to loop build_summary_v2 per learner and count how many learners
    each topic was weak *for*, low-confidence rows included. That was ~10
    queries per learner on the event loop the API shares (PERF-1), and a second
    definition of "weak": the stored paragraph and the brief could name
    different topics for one class. Now every read below is one query whatever
    the roster, and the topics are weak_topic_means() — class means at
    medium/high confidence, at or below the tutor's threshold.
    """
    subject = await session.get(Subject, group.subject_id)
    boundaries = boundaries_for(await org_boundaries(session, group.organization_id), subject)
    detail = await class_readiness(session, group.id)

    # Whose score rests on a tutor's estimate — build_summary_v2's own rule
    # (a scored Topic Mastery row carrying `tutor_estimate`), read for every
    # scored learner's latest run at once. class_readiness() only keeps the
    # flag per *topic mean*, and only at medium/high confidence; a seed
    # estimate alone scores at `low`, so without this read the commonest
    # estimate-backed score would reach the model as marked evidence (PROD-8).
    # Skipped when nobody is scored: there are no runs to look in, and an empty
    # IN () is a round trip on the shared event loop for nothing (PERF-1).
    run_ids = [s.evaluation_run_id for s in detail.scored]
    estimated = (
        {
            student_id
            for student_id, row_detail in (
                await session.execute(
                    select(FactorEvaluation.student_id, FactorEvaluation.detail).where(
                        FactorEvaluation.evaluation_run_id.in_(run_ids),
                        FactorEvaluation.factor == ReadinessFactor.topic_mastery,
                        FactorEvaluation.topic_id.is_not(None),
                        FactorEvaluation.score.is_not(None),
                        FactorEvaluation.confidence != FactorConfidence.no_data,
                    )
                )
            ).all()
            if "tutor_estimate" in (row_detail or {})
        }
        if run_ids
        else set()
    )

    low: list[str] = []
    unbanded: list[str] = []
    on_track = 0
    # Scored learners only, lowest first. An unscored learner has no status to
    # report: they are counted as "not enough data yet" below and never listed
    # here as a fabricated 0% (PROD-2).
    for s in detail.scored:
        if s.score is None:  # never, for `scored` — narrows the type
            continue
        line = f"- {s.student_name}: {round(s.score)}%"
        note = ESTIMATE_LABEL if s.student_id in estimated else ""
        # The snapshot's own grade, banded only while boundaries still stand
        # behind it — the rule the learner's profile and the class page apply.
        band = grade_band(s.predicted_grade if boundaries else None, boundaries)
        if band == "on_track":
            on_track += 1
        elif band is not None:
            low.append(f"{line} ({band}){note}")
        else:
            # No band is not "not on track". The score is real, so it still
            # reaches the model — with no status attached to it (PROD-2).
            unbanded.append(line + note)

    # Every count below is out of the learners it can actually be true of. Out
    # of the roster, "on track: 1 of 6" told the model five learners were off
    # track when five had no data; with no boundaries it said "0 of 1" and
    # "lower readiness: (none)" about a learner on 92% (PROD-2).
    scored_count = len(detail.scored)
    banded_count = scored_count - len(unbanded)
    counts = [
        f"Learners with a readiness score: {scored_count} of {scored_count + len(detail.unscored)}"
    ]
    if not boundaries:
        counts.append("No grade boundaries set — on-track status is not available.")
    elif banded_count:
        counts.append(f"On track: {on_track} of {banded_count}")
    if detail.unscored:
        counts.append(f"Not enough data yet: {len(detail.unscored)}")
    if estimated:
        counts.append(
            f"Learners whose readiness includes the tutor's starting estimate: {len(estimated)}"
        )

    learner_sections: list[str] = []
    if boundaries:
        if low or banded_count:
            nobody_low = "(none)"
        elif scored_count:
            nobody_low = "(no learner has an on-track status yet)"
        else:
            nobody_low = "(no learner has a readiness score yet)"
        learner_sections.append("Learners with lower readiness:\n" + ("\n".join(low) or nobody_low))
    if unbanded:
        heading = (
            "Scored, but no on-track status (no grade under the current boundaries):"
            if boundaries
            else "Learner readiness scores:"
        )
        learner_sections.append(heading + "\n" + "\n".join(unbanded))

    # Same line the class brief writes (api/groups.py), so the two paragraphs
    # about one class are grounded in the same words.
    weak_topics_text = "\n".join(
        f"- {t.topic_title} ({t.topic_code}): avg {t.avg_score}% across {t.student_count} learners"
        + (ESTIMATE_LABEL if t.includes_tutor_estimate else "")
        for t in (await weak_topic_means(session, group, detail))[:5]
    )
    # "None flagged" is a finding — every class mean is above the threshold. No
    # confident topic row at all is the absence of one, and says so (PROD-2).
    no_weak_topics = (
        "(none flagged)" if detail.topic_means else "(not enough confident topic data yet)"
    )
    return "\n\n".join(
        [
            f"AUDIENCE: tutor\nClass: {group.name} ({subject.name if subject else ''})\n"
            + "\n".join(counts),
            f"Weakest topics across the class:\n{weak_topics_text or no_weak_topics}",
            *learner_sections,
        ]
    )


async def _parent_grounding(session: AsyncSession, student: User) -> str:
    subject_ids = (
        await session.scalars(
            select(distinct(Group.subject_id))
            .join(GroupMember, GroupMember.group_id == Group.id)
            .where(GroupMember.student_id == student.id)
        )
    ).all()
    summary = await build_summary_v2(session, student, list(subject_ids))
    lines: list[str] = []
    for s in summary.subjects:
        if s.status is None:
            lines.append(f"- {s.subject_name}: not enough marked work yet")
            continue
        grade = s.predicted_grade or "no grade yet"
        direction = DIRECTION_WORDS.get(s.direction, "no trend yet")
        lines.append(
            f"- {s.subject_name}: {s.status}, predicted {grade} (estimate), {direction}, "
            f"from {s.marked_piece_count} marked piece(s){_estimate_note(s)}"
        )
    return f"AUDIENCE: parent\nChild: {student.name}\n\nSubjects:\n" + (
        "\n".join(lines) or "(no subjects yet)"
    )


# --------------------------------------------------------------------------- #
# Generation (the job handler) — idempotent, re-reads state, no-op when stale.
# --------------------------------------------------------------------------- #


async def _store(
    session: AsyncSession,
    *,
    audience: NarrativeAudience,
    organization_id: int,
    tutor_id: int | None,
    group_id: int | None,
    student_id: int | None,
    grounding: str,
) -> Narrative | None:
    """Generate the text and persist one row. Returns None (writing nothing) when
    the AI surface is unavailable — a missing key degrades the surface to its
    stated-absence state, it never blocks the worker or startup (AI-20, INF-9)."""
    template = get_prompt("narrative")
    try:
        response = await text_complete(surface="narrative", prompt=grounding, max_tokens=400)
    except AIUnavailableError:
        log.warning("narrative surface unavailable; leaving the surface in its absent state")
        return None

    narrative = Narrative(
        organization_id=organization_id,
        audience=audience,
        group_id=group_id,
        student_id=student_id,
        text=response.text.strip(),
        prompt_version=template.version,
        model=response.model,
        generated_at=datetime.now(timezone.utc),
    )
    session.add(narrative)
    if tutor_id is not None:
        await record_usage(
            session,
            response,
            organization_id=organization_id,
            tutor_id=tutor_id,
            student_id=student_id,
            feature=AiFeature.report,
        )
    await session.flush()
    return narrative


async def generate_narrative(session: AsyncSession, payload: dict) -> None:
    """Job handler. Payload carries identifiers only (BE-9); this re-reads live
    state, so re-running on the same payload with no new evidence writes nothing
    (BE-6)."""
    if not get_settings().narrative_enabled:
        return
    audience = NarrativeAudience(payload["audience"])
    # An explicit "Prepare again" must produce new text even with no new
    # evidence — that is what the control is for. The staleness check below is
    # what makes an ordinary re-run a no-op (BE-6).
    force = bool(payload.get("force"))

    if audience is NarrativeAudience.tutor_class:
        group = await session.get(Group, payload["group_id"])
        if group is None or group.deleted_at is not None:
            return
        latest_ev = await _latest_evidence_at_for_group(session, group)
        if latest_ev is None:
            return  # no marked evidence for this class yet — nothing to say
        existing = await latest_narrative(
            session,
            audience=audience,
            organization_id=group.organization_id,
            group_id=group.id,
        )
        if (
            not force
            and existing is not None
            and (generated := _aware(existing.generated_at)) is not None
            and generated >= latest_ev
        ):
            return  # nothing new since the last narrative — no-op re-run
        grounding = await _class_grounding(session, group)
        await _store(
            session,
            audience=audience,
            organization_id=group.organization_id,
            tutor_id=group.tutor_id,
            group_id=group.id,
            student_id=None,
            grounding=grounding,
        )
        return

    student = await session.get(User, payload["student_id"])
    if student is None:
        return
    latest_ev = await _latest_evidence_at_for_student(session, student.id)
    if latest_ev is None:
        return
    existing = await latest_narrative(
        session,
        audience=audience,
        organization_id=student.organization_id,
        student_id=student.id,
    )
    if (
        not force
        and existing is not None
        and (generated2 := _aware(existing.generated_at)) is not None
        and generated2 >= latest_ev
    ):
        return
    grounding = await _parent_grounding(session, student)
    tutor_id = await resolve_org_tutor_id(session, student.organization_id)
    await _store(
        session,
        audience=audience,
        organization_id=student.organization_id,
        tutor_id=tutor_id,
        group_id=None,
        student_id=student.id,
        grounding=grounding,
    )


# --------------------------------------------------------------------------- #
# Enqueue helpers and the weekly sweep.
# --------------------------------------------------------------------------- #


async def _pending_payloads(session: AsyncSession, job_type: str) -> list[dict]:
    # Compared in Python, not SQL: payload is a JSON column and Postgres' json
    # type has no equality operator (same as enqueue_readiness_v2_debounced).
    return list(
        (
            await session.scalars(
                select(Job.payload).where(Job.type == job_type, Job.status == JobStatus.pending)
            )
        ).all()
    )


async def _enqueue_one(
    session: AsyncSession, job_type: str, payload: dict, run_after: datetime | None = None
) -> None:
    """One job, flushed — for the single-row cases."""
    from app.workers.jobs import enqueue

    await enqueue(session, job_type, payload, run_after=run_after)


def _add_jobs(session: AsyncSession, job_type: str, payloads: list[dict]) -> None:
    """Queue several jobs with **one** flush, not one per row.

    workers/jobs.enqueue() flushes on every call, which is right for a single
    job and wrong for a loop: "Prepare again" on a class of thirty would pay
    thirty sequential round trips inside the tutor's request — the same N+1
    shape services/today.py exists to remove (PERF-1). The rows are added here
    and flushed once by the caller's commit.
    """
    session.add_all([Job(type=job_type, payload=payload) for payload in payloads])


async def enqueue_class_narratives_for_student_subject(
    session: AsyncSession, student_id: int, subject_id: int
) -> None:
    """Called at the tail of the evidence build. Enqueues a class narrative for
    each class the student belongs to in this subject, deduping against pending
    jobs so a burst of auto-finalized marks costs one narrative per class.

    **Scheduled behind the readiness recompute, not alongside it.** The grounding
    reads build_summary_v2, which prefers the latest *ready* snapshot, while the
    v2 run that would refresh that snapshot is itself debounced
    (readiness_v2_coalesce_seconds). Enqueued immediately, the narrative would be
    written from pre-marking readiness — and because its generated_at is then
    newer than the evidence, the staleness check below would treat that stale
    text as current until the *next* piece of evidence arrived. Waiting out the
    coalesce window costs nothing (this surface is read, never awaited) and makes
    the paragraph describe the readiness the tutor is looking at.
    """
    from app.workers.jobs import enqueue

    settings = get_settings()
    if not settings.narrative_enabled:
        return
    # A margin past the coalesce window so the v2 run has been claimed and
    # finished, not merely become due.
    run_after = datetime.now(timezone.utc) + timedelta(
        seconds=settings.readiness_v2_coalesce_seconds + settings.narrative_readiness_margin_seconds
    )
    group_ids = (
        await session.scalars(
            select(Group.id)
            .join(GroupMember, GroupMember.group_id == Group.id)
            .where(
                GroupMember.student_id == student_id,
                Group.subject_id == subject_id,
                Group.deleted_at.is_(None),
            )
        )
    ).all()
    pending = await _pending_payloads(session, CLASS_NARRATIVE_JOB)
    pending_groups = {
        p.get("group_id")
        for p in pending
        if p.get("audience") == NarrativeAudience.tutor_class.value
    }
    for gid in group_ids:
        if gid in pending_groups:
            continue
        await enqueue(
            session,
            CLASS_NARRATIVE_JOB,
            {"audience": NarrativeAudience.tutor_class.value, "group_id": gid},
            run_after=run_after,
        )


async def enqueue_narratives_for_group(session: AsyncSession, group_id: int) -> None:
    """ "Prepare again" for one class: refresh the tutor's class paragraph and the
    parent paragraph for every learner in it.

    This is D2's correction mechanism. There is no approval step and no review
    state, so a tutor who reads something wrong regenerates it rather than
    approving it. Forced: unlike the job's own staleness check, an explicit
    regenerate must produce new text even when no new evidence has landed —
    that is the entire point of the control.
    """
    if not get_settings().narrative_enabled:
        return
    student_ids = (
        await session.scalars(
            select(GroupMember.student_id).where(GroupMember.group_id == group_id)
        )
    ).all()
    # One flush for the whole class, not one per learner — this runs inside the
    # tutor's own request.
    _add_jobs(
        session,
        CLASS_NARRATIVE_JOB,
        [
            {
                "audience": NarrativeAudience.tutor_class.value,
                "group_id": group_id,
                "force": True,
            },
            *(
                {
                    "audience": NarrativeAudience.parent_student.value,
                    "student_id": sid,
                    "force": True,
                }
                for sid in student_ids
            ),
        ],
    )


async def _reenqueue_sweep(session: AsyncSession) -> None:
    """Keep exactly one sweep pending, scheduled one interval out."""
    from app.workers.jobs import enqueue

    if await _pending_payloads(session, SWEEP_JOB):
        return
    interval = get_settings().narrative_sweep_interval_hours
    await enqueue(
        session,
        SWEEP_JOB,
        {},
        run_after=datetime.now(timezone.utc) + timedelta(hours=interval),
    )


async def ensure_narrative_sweep_scheduled(session: AsyncSession) -> None:
    """Startup floor: if no sweep is pending, schedule one. Idempotent, so a
    restart heals a lost schedule without accumulating sweep rows — the one
    thing worth this belt-and-braces, because if the sweep row is ever lost
    every parent narrative stops."""
    from app.workers.jobs import enqueue

    if await _pending_payloads(session, SWEEP_JOB):
        return
    await enqueue(session, SWEEP_JOB, {})


async def _commit_successor_sweep() -> None:
    """Queue the next sweep in its **own committed transaction**.

    This is the whole reliability story, so it does not share the handler's
    session. workers/jobs.py runs a handler inside one session and commits only
    on success: if the sweep body raises, that session is rolled back, and a
    successor enqueued on it disappears with everything else. After MAX_ATTEMPTS
    the job is marked failed, nothing watches that (jobs.py says so explicitly),
    and every parent narrative stops until the process restarts — the exact
    silent-death failure the sweep design exists to avoid, reintroduced one
    level up. Committing the successor separately, before the work, means the
    schedule survives any outcome of that work.
    """
    async with async_session() as session:
        if await _pending_payloads(session, SWEEP_JOB):
            return
        interval = get_settings().narrative_sweep_interval_hours
        await _enqueue_one(
            session,
            SWEEP_JOB,
            {},
            run_after=datetime.now(timezone.utc) + timedelta(hours=interval),
        )
        await session.commit()


async def sweep_parent_narratives(session: AsyncSession, payload: dict) -> None:
    """Weekly-ish sweep. Re-derives which students are due from the narratives
    table and enqueues one generate_narrative each.

    The successor sweep is committed FIRST, in its own transaction, so the
    schedule survives this run failing — see _commit_successor_sweep(). An
    individual narrative failing was always safe (each is its own job); a
    failing *sweep* was not, and that is what this ordering fixes.
    """
    settings = get_settings()
    await _commit_successor_sweep()
    # Nothing further to do when the kill switch is off, but the schedule above
    # is already re-armed, so flipping it back on resumes without a restart.
    if not settings.narrative_enabled:
        return

    cutoff = datetime.now(timezone.utc) - timedelta(days=settings.narrative_parent_max_age_days)
    # Students who have some evidence — enrolled learners with a marked-work row.
    student_ids = (
        await session.scalars(
            select(distinct(User.id))
            .join(GroupMember, GroupMember.student_id == User.id)
            .join(Group, Group.id == GroupMember.group_id)
            .join(Evidence, Evidence.student_id == User.id)
            .where(
                User.role == UserRole.student,
                COUNTS_FOR_READINESS,
                # A student whose classes are all deleted is no longer written about.
                Group.deleted_at.is_(None),
            )
        )
    ).all()

    pending = await _pending_payloads(session, CLASS_NARRATIVE_JOB)
    pending_students = {
        p.get("student_id")
        for p in pending
        if p.get("audience") == NarrativeAudience.parent_student.value
    }

    # When each narrative's freshness was read one student at a time, the sweep
    # cost two round trips per learner and its duration grew with the whole
    # installed base — the same fan-out class_health() exists to remove
    # (PERF-1). Both facts now arrive in one grouped query each.
    #
    # The freshness lookup keys on (student, organization) rather than student
    # alone, which is what latest_narrative() scoped by: a learner who moved
    # organizations must not be held back by the paragraph written about them
    # under their old one.
    freshest: dict[int, datetime | None] = {}
    if student_ids:
        newest_per_student = (
            select(func.max(Narrative.id))
            .join(User, User.id == Narrative.student_id)
            .where(
                Narrative.audience == NarrativeAudience.parent_student,
                Narrative.student_id.in_(student_ids),
                Narrative.organization_id == User.organization_id,
            )
            .group_by(Narrative.student_id)
        )
        for sid, generated_at in (
            await session.execute(
                select(Narrative.student_id, Narrative.generated_at).where(
                    Narrative.id.in_(newest_per_student)
                )
            )
        ).all():
            freshest[sid] = _aware(generated_at)

    # One cycle's work is capped. Without it a first run against an established
    # installation enqueues one AI job per learner at once — real money, spent
    # in a burst, for paragraphs nobody has asked for yet. The set is re-derived
    # every sweep and an enqueued learner stops being due, so a backlog drains
    # over consecutive runs instead of arriving as one spike.
    due = [
        sid
        for sid in student_ids
        if sid not in pending_students
        and not ((generated := freshest.get(sid)) is not None and generated >= cutoff)
    ]
    # One flush for the batch, not one per learner: enqueue() flushes on every
    # call, which is right for a single job and wrong for a loop this long.
    _add_jobs(
        session,
        CLASS_NARRATIVE_JOB,
        [
            {"audience": NarrativeAudience.parent_student.value, "student_id": sid}
            for sid in due[: settings.narrative_sweep_max_students]
        ],
    )
