"""The precomputed narrative — stored plain-prose paragraphs for the tutor's
home / class page (about a class) and the parent screen (about a child).

Spec §8: the narrative is present when the surface opens; no primary surface
waits on a model to render its primary content. So the text is generated by a
background job and stored (models/narrative.py); surfaces read the latest row.
Contrast POST /groups/{id}/brief, which builds the same kind of text live and
discards it.

Two triggers, deliberately different in shape:

- The class narrative enqueues when marked evidence lands for that class, at the
  tail of the evidence build (services/marking.record_marks_as_evidence).
- The parent narrative refreshes weekly by SWEEP, not by a self-perpetuating
  chain. A chain would keep the whole schedule inside one job row, and
  workers/jobs.py sets status=failed at MAX_ATTEMPTS with nothing watching it —
  so one transient AI outage across the retry window would end a parent's
  updates permanently and silently. The sweep re-derives who is due from the
  narratives table every run (BE-9), so a failed sweep costs one cycle and
  self-corrects; a failed individual narrative costs one cycle for one student.

Everything here is gated on settings.narrative_enabled — the kill switch that
stops new narratives while leaving stored ones readable.
"""

import logging
from datetime import datetime, timedelta, timezone

from sqlalchemy import distinct, func, select
from sqlalchemy.ext.asyncio import AsyncSession

from app.config import get_settings
from app.db import async_session
from app.models import (
    AiFeature,
    Evidence,
    Group,
    GroupMember,
    Job,
    JobStatus,
    Narrative,
    NarrativeAudience,
    Topic,
    User,
    UserRole,
)
from app.services.ai import AIUnavailableError, record_usage, text_complete
from app.services.knowledge import resolve_org_tutor_id
from app.services.prompts import get_prompt
from app.services.readiness_summary_v2 import build_summary_v2

log = logging.getLogger("narrative")

CLASS_NARRATIVE_JOB = "generate_narrative"
SWEEP_JOB = "sweep_parent_narratives"

DIRECTION_WORDS = {"up": "improving", "down": "declining", "flat": "steady", None: "no trend yet"}


def _aware(value: datetime | None) -> datetime | None:
    """SQLite hands back tz-naive datetimes where Postgres returns aware, and
    comparing the two raises. The stored value is UTC either way."""
    if value is None:
        return None
    return value if value.tzinfo is not None else value.replace(tzinfo=timezone.utc)


# --------------------------------------------------------------------------- #
# Reading the latest stored narrative (also used by the PR 15 read endpoints).
# --------------------------------------------------------------------------- #


async def latest_narrative(
    session: AsyncSession,
    *,
    audience: NarrativeAudience,
    organization_id: int,
    group_id: int | None = None,
    student_id: int | None = None,
) -> Narrative | None:
    """The most recent narrative for one target, ordered by id (not generated_at)
    so a manual regenerate racing the sweep resolves deterministically."""
    stmt = select(Narrative).where(
        Narrative.organization_id == organization_id,
        Narrative.audience == audience,
    )
    if audience is NarrativeAudience.tutor_class:
        stmt = stmt.where(Narrative.group_id == group_id)
    else:
        stmt = stmt.where(Narrative.student_id == student_id)
    return await session.scalar(stmt.order_by(Narrative.id.desc()).limit(1))


# --------------------------------------------------------------------------- #
# Grounding — facts already computed from real evidence, never invented.
# --------------------------------------------------------------------------- #


async def _latest_evidence_at_for_group(session: AsyncSession, group: Group) -> datetime | None:
    return _aware(
        await session.scalar(
            select(func.max(Evidence.occurred_at))
            .select_from(Evidence)
            .join(Topic, Topic.id == Evidence.topic_id)
            .join(GroupMember, GroupMember.student_id == Evidence.student_id)
            .where(GroupMember.group_id == group.id, Topic.subject_id == group.subject_id)
        )
    )


async def _latest_evidence_at_for_student(
    session: AsyncSession, student_id: int
) -> datetime | None:
    return _aware(
        await session.scalar(
            select(func.max(Evidence.occurred_at)).where(Evidence.student_id == student_id)
        )
    )


async def _class_grounding(session: AsyncSession, group: Group) -> str:
    members = (
        await session.scalars(
            select(User)
            .join(GroupMember, GroupMember.student_id == User.id)
            .where(GroupMember.group_id == group.id)
        )
    ).all()
    subject_name = ""
    low: list[str] = []
    on_track = 0
    weak_topic_counts: dict[str, int] = {}
    for member in members:
        summary = await build_summary_v2(session, member, [group.subject_id])
        if not summary.subjects:
            continue
        s = summary.subjects[0]
        subject_name = s.subject_name
        if s.status == "on_track":
            on_track += 1
        elif s.status is not None:
            score = f"{round(s.score)}%" if s.score is not None else "not enough data yet"
            low.append(f"- {member.name}: {score} ({s.status})")
        for wt in s.weak_topics:
            weak_topic_counts[f"{wt.topic_code} {wt.topic_title}"] = (
                weak_topic_counts.get(f"{wt.topic_code} {wt.topic_title}", 0) + 1
            )
    weak_topics = sorted(weak_topic_counts.items(), key=lambda kv: -kv[1])[:5]
    weak_topics_text = "\n".join(f"- {name} (weak for {n} learners)" for name, n in weak_topics)
    return (
        "AUDIENCE: tutor\n"
        f"Class: {group.name} ({subject_name})\n"
        f"Learners on track: {on_track} of {len(members)}\n\n"
        f"Weakest topics across the class:\n{weak_topics_text or '(none flagged)'}\n\n"
        f"Learners with lower readiness:\n" + ("\n".join(low) or "(none)")
    )


async def _parent_grounding(session: AsyncSession, student: User) -> str:
    subject_ids = (
        await session.scalars(
            select(distinct(Group.subject_id))
            .join(GroupMember, GroupMember.group_id == Group.id)
            .where(GroupMember.student_id == student.id)
        )
    ).all()
    summary = await build_summary_v2(session, student, list(subject_ids))
    lines: list[str] = []
    for s in summary.subjects:
        if s.status is None:
            lines.append(f"- {s.subject_name}: not enough marked work yet")
            continue
        grade = s.predicted_grade or "no grade yet"
        direction = DIRECTION_WORDS.get(s.direction, "no trend yet")
        lines.append(
            f"- {s.subject_name}: {s.status}, predicted {grade} (estimate), {direction}, "
            f"from {s.marked_piece_count} marked piece(s)"
        )
    return f"AUDIENCE: parent\nChild: {student.name}\n\nSubjects:\n" + (
        "\n".join(lines) or "(no subjects yet)"
    )


# --------------------------------------------------------------------------- #
# Generation (the job handler) — idempotent, re-reads state, no-op when stale.
# --------------------------------------------------------------------------- #


async def _store(
    session: AsyncSession,
    *,
    audience: NarrativeAudience,
    organization_id: int,
    tutor_id: int | None,
    group_id: int | None,
    student_id: int | None,
    grounding: str,
) -> Narrative | None:
    """Generate the text and persist one row. Returns None (writing nothing) when
    the AI surface is unavailable — a missing key degrades the surface to its
    stated-absence state, it never blocks the worker or startup (AI-20, INF-9)."""
    template = get_prompt("narrative")
    try:
        response = await text_complete(surface="narrative", prompt=grounding, max_tokens=400)
    except AIUnavailableError:
        log.warning("narrative surface unavailable; leaving the surface in its absent state")
        return None

    narrative = Narrative(
        organization_id=organization_id,
        audience=audience,
        group_id=group_id,
        student_id=student_id,
        text=response.text.strip(),
        prompt_version=template.version,
        model=response.model,
        generated_at=datetime.now(timezone.utc),
    )
    session.add(narrative)
    if tutor_id is not None:
        await record_usage(
            session,
            response,
            organization_id=organization_id,
            tutor_id=tutor_id,
            student_id=student_id,
            feature=AiFeature.report,
        )
    await session.flush()
    return narrative


async def generate_narrative(session: AsyncSession, payload: dict) -> None:
    """Job handler. Payload carries identifiers only (BE-9); this re-reads live
    state, so re-running on the same payload with no new evidence writes nothing
    (BE-6)."""
    if not get_settings().narrative_enabled:
        return
    audience = NarrativeAudience(payload["audience"])
    # An explicit "Prepare again" must produce new text even with no new
    # evidence — that is what the control is for. The staleness check below is
    # what makes an ordinary re-run a no-op (BE-6).
    force = bool(payload.get("force"))

    if audience is NarrativeAudience.tutor_class:
        group = await session.get(Group, payload["group_id"])
        if group is None:
            return
        latest_ev = await _latest_evidence_at_for_group(session, group)
        if latest_ev is None:
            return  # no marked evidence for this class yet — nothing to say
        existing = await latest_narrative(
            session,
            audience=audience,
            organization_id=group.organization_id,
            group_id=group.id,
        )
        if not force and existing is not None and _aware(existing.generated_at) >= latest_ev:
            return  # nothing new since the last narrative — no-op re-run
        grounding = await _class_grounding(session, group)
        await _store(
            session,
            audience=audience,
            organization_id=group.organization_id,
            tutor_id=group.tutor_id,
            group_id=group.id,
            student_id=None,
            grounding=grounding,
        )
        return

    student = await session.get(User, payload["student_id"])
    if student is None:
        return
    latest_ev = await _latest_evidence_at_for_student(session, student.id)
    if latest_ev is None:
        return
    existing = await latest_narrative(
        session,
        audience=audience,
        organization_id=student.organization_id,
        student_id=student.id,
    )
    if not force and existing is not None and _aware(existing.generated_at) >= latest_ev:
        return
    grounding = await _parent_grounding(session, student)
    tutor_id = await resolve_org_tutor_id(session, student.organization_id)
    await _store(
        session,
        audience=audience,
        organization_id=student.organization_id,
        tutor_id=tutor_id,
        group_id=None,
        student_id=student.id,
        grounding=grounding,
    )


# --------------------------------------------------------------------------- #
# Enqueue helpers and the weekly sweep.
# --------------------------------------------------------------------------- #


async def _pending_payloads(session: AsyncSession, job_type: str) -> list[dict]:
    # Compared in Python, not SQL: payload is a JSON column and Postgres' json
    # type has no equality operator (same as enqueue_readiness_v2_debounced).
    return list(
        (
            await session.scalars(
                select(Job.payload).where(Job.type == job_type, Job.status == JobStatus.pending)
            )
        ).all()
    )


async def _enqueue_one(
    session: AsyncSession, job_type: str, payload: dict, run_after: datetime | None = None
) -> None:
    """One job, flushed — for the single-row cases."""
    from app.workers.jobs import enqueue

    await enqueue(session, job_type, payload, run_after=run_after)


def _add_jobs(session: AsyncSession, job_type: str, payloads: list[dict]) -> None:
    """Queue several jobs with **one** flush, not one per row.

    workers/jobs.enqueue() flushes on every call, which is right for a single
    job and wrong for a loop: "Prepare again" on a class of thirty would pay
    thirty sequential round trips inside the tutor's request — the same N+1
    shape services/today.py exists to remove (PERF-1). The rows are added here
    and flushed once by the caller's commit.
    """
    session.add_all([Job(type=job_type, payload=payload) for payload in payloads])


async def enqueue_class_narratives_for_student_subject(
    session: AsyncSession, student_id: int, subject_id: int
) -> None:
    """Called at the tail of the evidence build. Enqueues a class narrative for
    each class the student belongs to in this subject, deduping against pending
    jobs so a burst of auto-finalized marks costs one narrative per class.

    **Scheduled behind the readiness recompute, not alongside it.** The grounding
    reads build_summary_v2, which prefers the latest *ready* snapshot, while the
    v2 run that would refresh that snapshot is itself debounced
    (readiness_v2_coalesce_seconds). Enqueued immediately, the narrative would be
    written from pre-marking readiness — and because its generated_at is then
    newer than the evidence, the staleness check below would treat that stale
    text as current until the *next* piece of evidence arrived. Waiting out the
    coalesce window costs nothing (this surface is read, never awaited) and makes
    the paragraph describe the readiness the tutor is looking at.
    """
    from app.workers.jobs import enqueue

    settings = get_settings()
    if not settings.narrative_enabled:
        return
    # A margin past the coalesce window so the v2 run has been claimed and
    # finished, not merely become due.
    run_after = datetime.now(timezone.utc) + timedelta(
        seconds=settings.readiness_v2_coalesce_seconds + settings.narrative_readiness_margin_seconds
    )
    group_ids = (
        await session.scalars(
            select(Group.id)
            .join(GroupMember, GroupMember.group_id == Group.id)
            .where(GroupMember.student_id == student_id, Group.subject_id == subject_id)
        )
    ).all()
    pending = await _pending_payloads(session, CLASS_NARRATIVE_JOB)
    pending_groups = {
        p.get("group_id")
        for p in pending
        if p.get("audience") == NarrativeAudience.tutor_class.value
    }
    for gid in group_ids:
        if gid in pending_groups:
            continue
        await enqueue(
            session,
            CLASS_NARRATIVE_JOB,
            {"audience": NarrativeAudience.tutor_class.value, "group_id": gid},
            run_after=run_after,
        )


async def enqueue_narratives_for_group(session: AsyncSession, group_id: int) -> None:
    """ "Prepare again" for one class: refresh the tutor's class paragraph and the
    parent paragraph for every learner in it.

    This is D2's correction mechanism. There is no approval step and no review
    state, so a tutor who reads something wrong regenerates it rather than
    approving it. Forced: unlike the job's own staleness check, an explicit
    regenerate must produce new text even when no new evidence has landed —
    that is the entire point of the control.
    """
    if not get_settings().narrative_enabled:
        return
    student_ids = (
        await session.scalars(
            select(GroupMember.student_id).where(GroupMember.group_id == group_id)
        )
    ).all()
    # One flush for the whole class, not one per learner — this runs inside the
    # tutor's own request.
    _add_jobs(
        session,
        CLASS_NARRATIVE_JOB,
        [
            {
                "audience": NarrativeAudience.tutor_class.value,
                "group_id": group_id,
                "force": True,
            },
            *(
                {
                    "audience": NarrativeAudience.parent_student.value,
                    "student_id": sid,
                    "force": True,
                }
                for sid in student_ids
            ),
        ],
    )


async def _reenqueue_sweep(session: AsyncSession) -> None:
    """Keep exactly one sweep pending, scheduled one interval out."""
    from app.workers.jobs import enqueue

    if await _pending_payloads(session, SWEEP_JOB):
        return
    interval = get_settings().narrative_sweep_interval_hours
    await enqueue(
        session,
        SWEEP_JOB,
        {},
        run_after=datetime.now(timezone.utc) + timedelta(hours=interval),
    )


async def ensure_narrative_sweep_scheduled(session: AsyncSession) -> None:
    """Startup floor: if no sweep is pending, schedule one. Idempotent, so a
    restart heals a lost schedule without accumulating sweep rows — the one
    thing worth this belt-and-braces, because if the sweep row is ever lost
    every parent narrative stops."""
    from app.workers.jobs import enqueue

    if await _pending_payloads(session, SWEEP_JOB):
        return
    await enqueue(session, SWEEP_JOB, {})


async def _commit_successor_sweep() -> None:
    """Queue the next sweep in its **own committed transaction**.

    This is the whole reliability story, so it does not share the handler's
    session. workers/jobs.py runs a handler inside one session and commits only
    on success: if the sweep body raises, that session is rolled back, and a
    successor enqueued on it disappears with everything else. After MAX_ATTEMPTS
    the job is marked failed, nothing watches that (jobs.py says so explicitly),
    and every parent narrative stops until the process restarts — the exact
    silent-death failure the sweep design exists to avoid, reintroduced one
    level up. Committing the successor separately, before the work, means the
    schedule survives any outcome of that work.
    """
    async with async_session() as session:
        if await _pending_payloads(session, SWEEP_JOB):
            return
        interval = get_settings().narrative_sweep_interval_hours
        await _enqueue_one(
            session,
            SWEEP_JOB,
            {},
            run_after=datetime.now(timezone.utc) + timedelta(hours=interval),
        )
        await session.commit()


async def sweep_parent_narratives(session: AsyncSession, payload: dict) -> None:
    """Weekly-ish sweep. Re-derives which students are due from the narratives
    table and enqueues one generate_narrative each.

    The successor sweep is committed FIRST, in its own transaction, so the
    schedule survives this run failing — see _commit_successor_sweep(). An
    individual narrative failing was always safe (each is its own job); a
    failing *sweep* was not, and that is what this ordering fixes.
    """
    settings = get_settings()
    await _commit_successor_sweep()
    # Nothing further to do when the kill switch is off, but the schedule above
    # is already re-armed, so flipping it back on resumes without a restart.
    if not settings.narrative_enabled:
        return

    from app.workers.jobs import enqueue

    cutoff = datetime.now(timezone.utc) - timedelta(days=settings.narrative_parent_max_age_days)
    # Students who have some evidence — enrolled learners with a marked-work row.
    student_ids = (
        await session.scalars(
            select(distinct(User.id))
            .join(GroupMember, GroupMember.student_id == User.id)
            .join(Evidence, Evidence.student_id == User.id)
            .where(User.role == UserRole.student)
        )
    ).all()

    pending = await _pending_payloads(session, CLASS_NARRATIVE_JOB)
    pending_students = {
        p.get("student_id")
        for p in pending
        if p.get("audience") == NarrativeAudience.parent_student.value
    }

    for sid in student_ids:
        if sid in pending_students:
            continue
        student = await session.get(User, sid)
        if student is None:
            continue
        existing = await latest_narrative(
            session,
            audience=NarrativeAudience.parent_student,
            organization_id=student.organization_id,
            student_id=sid,
        )
        if existing is not None and _aware(existing.generated_at) >= cutoff:
            continue  # fresh enough — not due
        await enqueue(
            session,
            CLASS_NARRATIVE_JOB,
            {"audience": NarrativeAudience.parent_student.value, "student_id": sid},
        )
