"""Read surfaces for the stored narrative.

The text is generated by a background job and stored (services/narrative.py), so
these endpoints are a seek, not an AI call — spec §8: no primary surface waits on
a model to render its primary content.

Per D2 there is no review or suppress endpoint, and the row carries no review
state. A tutor who reads something wrong regenerates it via the existing
POST /groups/{id}/brief ("Prepare again"), which is a correction rather than a
gate.

Scoping: the organization comes from the authenticated user, never from a path or
body parameter (SEC-7). Anything the caller may not know exists returns 404, not
403, because integer keys are enumerable (API-7 / SEC-9). Role gates live in the
signature (SEC-11 / BE-17) — a dependency cannot be forgotten, an imperative call
can, and omitting one fails open.
"""

from fastapi import APIRouter, HTTPException, status
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.api.deps import CurrentUser, DbSession, TutorUser
from app.models import (
    Group,
    NarrativeAudience,
    ParentLink,
    User,
    UserRole,
)
from app.schemas.narrative import NarrativeOut
from app.services.narrative import latest_narrative

router = APIRouter(tags=["narrative"])


def _out(narrative) -> NarrativeOut:
    """A stated absence is a first-class response, never an empty string that a
    surface would render as a blank panel (PROD-2 / UX-19)."""
    if narrative is None:
        return NarrativeOut(text=None, generated_at=None, prompt_version=None)
    return NarrativeOut(
        text=narrative.text,
        generated_at=narrative.generated_at,
        prompt_version=narrative.prompt_version,
    )


async def _owned_group(db: AsyncSession, user: User, group_id: int) -> Group:
    group = await db.get(Group, group_id)
    if group is None or (group.tutor_id != user.id and user.role != UserRole.admin):
        raise HTTPException(status.HTTP_404_NOT_FOUND, "Group not found")
    return group


@router.get("/groups/{group_id}/narrative", response_model=NarrativeOut)
async def group_narrative(group_id: int, db: DbSession, user: TutorUser) -> NarrativeOut:
    """The stored class narrative — what the tutor's home and class page read."""
    group = await _owned_group(db, user, group_id)
    return _out(
        await latest_narrative(
            db,
            audience=NarrativeAudience.tutor_class,
            organization_id=group.organization_id,
            group_id=group.id,
        )
    )


@router.get("/students/{student_id}/narrative", response_model=NarrativeOut)
async def student_narrative(student_id: int, db: DbSession, user: CurrentUser) -> NarrativeOut:
    """The stored parent narrative about one child.

    Readable by that child's linked parent, by a tutor who actually teaches them,
    and by an admin. Everyone else gets 404 — including a parent asking about a
    child who is not theirs, and anyone in another organization, because a 403
    would confirm the row exists.
    """
    student = await db.get(User, student_id)
    if student is None or student.role != UserRole.student:
        raise HTTPException(status.HTTP_404_NOT_FOUND, "Student not found")

    if user.role == UserRole.parent:
        link = await db.scalar(
            select(ParentLink).where(
                ParentLink.parent_id == user.id, ParentLink.student_id == student_id
            )
        )
        if link is None:
            raise HTTPException(status.HTTP_404_NOT_FOUND, "Student not found")
    elif user.role == UserRole.tutor:
        # Scoped by the groups this tutor owns, so a tutor in another
        # organization cannot read it even though subjects are global (SEC-8).
        from app.models import GroupMember

        teaches = await db.scalar(
            select(Group.id)
            .join(GroupMember, GroupMember.group_id == Group.id)
            .where(GroupMember.student_id == student_id, Group.tutor_id == user.id)
            .limit(1)
        )
        if teaches is None:
            raise HTTPException(status.HTTP_404_NOT_FOUND, "Student not found")
    elif user.role == UserRole.student:
        # A student does not read the paragraph written for their parent.
        raise HTTPException(status.HTTP_404_NOT_FOUND, "Student not found")
    elif user.role != UserRole.admin:
        raise HTTPException(status.HTTP_404_NOT_FOUND, "Student not found")

    return _out(
        await latest_narrative(
            db,
            audience=NarrativeAudience.parent_student,
            organization_id=student.organization_id,
            student_id=student.id,
        )
    )
